# Generated by Django 2.0.3 on 2018-03-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='disliked_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
    ]
