# Generated by Django 2.0.4 on 2018-04-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180402_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='tag',
            name='body',
            field=models.TextField(db_index=True, max_length=50, unique=True),
        ),
    ]
