# Generated by Django 2.0.2 on 2018-03-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followees',
            field=models.ManyToManyField(related_name='followers', to='profiles.Profile'),
        ),
    ]
