# Generated by Django 2.0.3 on 2018-03-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180330_1704'),
        ('profiles', '0003_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disliked_posts',
            field=models.ManyToManyField(related_name='disliked_by', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_by', to='posts.Post'),
        ),
    ]
